### ISSUE TITLE
Multiple ppp conversions: unexpected behavior

### ISSUE THREAD

**Issue by jkpr** [jkpr/pmix#40]
Should have a default output folder?

`-o` does not seem to do the correct thing in the multi-file conversion?

What do you think, @joeflack4?

![screenshot 2018-05-17 15 48 43](https://user-images.githubusercontent.com/3988950/40200313-f607aa48-59e9-11e8-8c61-97cab051ed73.png)

**Comment by joeflack4** [comment]
Thanks for the screenshot. Definitely an issue.

So to re-iterate, 2 problems:
- The `--output` option (`-o`) does not output files where specified.
- It also ends up actually naming every file whatever the value of `-o` specified is.

### Example
`python -m pmix.ppp [files] -o myFolder`
#### Expected Result
Files should be saved in "myFolder".

#### Actual Result
A single file named simply "myFolder" is saved in the present working directory.

**Comment by joeflack4** [comment]
@jkpr You may close issue. Migrated to: https://github.com/PMA-2020/ppp/issues/1
